<?php
// packages\vsent\TableConfigurations\src\Database\Seeders\TableConfigurationsSeeder.php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TableConfigurationsSeeder extends Seeder
{
    public function run(): void
    {
        $table = 'products';

        $columns = [
            [
                'column_name' => 'id',
                'data_type' => 'BIGINT',
                'length_or_values' => null,
                'default_value' => null,
                'character_collation' => null,
                'column_attributes' => 'UNSIGNED AUTO_INCREMENT',
                'is_nullable' => false,
                'index_type' => 'PRIMARY',
                'is_auto_increment' => true,
                'column_comments' => 'Primary key',
            ],
            [
                'column_name' => 'product_code',
                'data_type' => 'VARCHAR',
                'length_or_values' => '50',
                'default_value' => null,
                'character_collation' => 'utf8mb4_unicode_ci',
                'column_attributes' => null,
                'is_nullable' => false,
                'index_type' => 'UNIQUE',
                'is_auto_increment' => false,
                'column_comments' => 'Unique manufacturer code',
            ],
            [
                'column_name' => 'model_name',
                'data_type' => 'VARCHAR',
                'length_or_values' => '100',
                'default_value' => null,
                'character_collation' => 'utf8mb4_unicode_ci',
                'column_attributes' => null,
                'is_nullable' => false,
                'index_type' => null,
                'is_auto_increment' => false,
                'column_comments' => 'Short product name',
            ],
            [
                'column_name' => 'brand',
                'data_type' => 'VARCHAR',
                'length_or_values' => '50',
                'default_value' => null,
                'character_collation' => 'utf8mb4_unicode_ci',
                'column_attributes' => null,
                'is_nullable' => false,
                'index_type' => 'INDEX',
                'is_auto_increment' => false,
                'column_comments' => 'Brand name',
            ],
            [
                'column_name' => 'product_category',
                'data_type' => 'VARCHAR',
                'length_or_values' => '30',
                'default_value' => null,
                'character_collation' => 'utf8mb4_unicode_ci',
                'column_attributes' => null,
                'is_nullable' => false,
                'index_type' => 'INDEX',
                'is_auto_increment' => false,
                'column_comments' => 'Product type',
            ],
            [
                'column_name' => 'ram',
                'data_type' => 'VARCHAR',
                'length_or_values' => '20',
                'default_value' => null,
                'character_collation' => 'utf8mb4_unicode_ci',
                'column_attributes' => null,
                'is_nullable' => true,
                'index_type' => null,
                'is_auto_increment' => false,
                'column_comments' => 'RAM size',
            ],
            [
                'column_name' => 'storage',
                'data_type' => 'VARCHAR',
                'length_or_values' => '20',
                'default_value' => null,
                'character_collation' => 'utf8mb4_unicode_ci',
                'column_attributes' => null,
                'is_nullable' => true,
                'index_type' => null,
                'is_auto_increment' => false,
                'column_comments' => 'Storage capacity',
            ],
            [
                'column_name' => 'price_mrp',
                'data_type' => 'DECIMAL',
                'length_or_values' => '12,2',
                'default_value' => null,
                'character_collation' => null,
                'column_attributes' => null,
                'is_nullable' => false,
                'index_type' => null,
                'is_auto_increment' => false,
                'column_comments' => 'Maximum retail price',
            ],
            [
                'column_name' => 'currency',
                'data_type' => 'VARCHAR',
                'length_or_values' => '3',
                'default_value' => 'USD',
                'character_collation' => 'utf8mb4_unicode_ci',
                'column_attributes' => null,
                'is_nullable' => false,
                'index_type' => null,
                'is_auto_increment' => false,
                'column_comments' => 'Currency code',
            ],
            [
                'column_name' => 'stock_quantity',
                'data_type' => 'INT',
                'length_or_values' => null,
                'default_value' => '0',
                'character_collation' => null,
                'column_attributes' => null,
                'is_nullable' => false,
                'index_type' => null,
                'is_auto_increment' => false,
                'column_comments' => 'Inventory count',
            ],
            [
                'column_name' => 'stock_status',
                'data_type' => 'ENUM',
                'length_or_values' => 'in_stock,out_of_stock,pre_order',
                'default_value' => 'in_stock',
                'character_collation' => 'utf8mb4_unicode_ci',
                'column_attributes' => null,
                'is_nullable' => false,
                'index_type' => null,
                'is_auto_increment' => false,
                'column_comments' => 'Inventory status',
            ],
            [
                'column_name' => 'is_featured',
                'data_type' => 'TINYINT',
                'length_or_values' => '1',
                'default_value' => '0',
                'character_collation' => null,
                'column_attributes' => null,
                'is_nullable' => false,
                'index_type' => null,
                'is_auto_increment' => false,
                'column_comments' => 'Featured product flag',
            ],
            [
                'column_name' => 'status',
                'data_type' => 'ENUM',
                'length_or_values' => 'active,inactive,discontinued',
                'default_value' => 'active',
                'character_collation' => 'utf8mb4_unicode_ci',
                'column_attributes' => null,
                'is_nullable' => false,
                'index_type' => null,
                'is_auto_increment' => false,
                'column_comments' => 'Product status',
            ],
            [
                'column_name' => 'created_at',
                'data_type' => 'TIMESTAMP',
                'length_or_values' => null,
                'default_value' => null,
                'character_collation' => null,
                'column_attributes' => null,
                'is_nullable' => true,
                'index_type' => null,
                'is_auto_increment' => false,
                'column_comments' => 'Creation timestamp',
            ],
            [
                'column_name' => 'updated_at',
                'data_type' => 'TIMESTAMP',
                'length_or_values' => null,
                'default_value' => null,
                'character_collation' => null,
                'column_attributes' => null,
                'is_nullable' => true,
                'index_type' => null,
                'is_auto_increment' => false,
                'column_comments' => 'Update timestamp',
            ],
            [
                'column_name' => 'deleted_at',
                'data_type' => 'TIMESTAMP',
                'length_or_values' => null,
                'default_value' => null,
                'character_collation' => null,
                'column_attributes' => null,
                'is_nullable' => true,
                'index_type' => null,
                'is_auto_increment' => false,
                'column_comments' => 'Deleted timestamp',
            ],
            [
                'column_name' => 'restored_at',
                'data_type' => 'TIMESTAMP',
                'length_or_values' => null,
                'default_value' => null,
                'character_collation' => null,
                'column_attributes' => null,
                'is_nullable' => true,
                'index_type' => null,
                'is_auto_increment' => false,
                'column_comments' => 'Restored timestamp',
            ],
            [
                'column_name' => 'created_by',
                'data_type' => 'BIGINT',
                'length_or_values' => null,
                'default_value' => null,
                'character_collation' => null,
                'column_attributes' => 'UNSIGNED',
                'is_nullable' => true,
                'index_type' => null,
                'is_auto_increment' => false,
                'column_comments' => 'User who created the record',
            ],
            [
                'column_name' => 'updated_by',
                'data_type' => 'BIGINT',
                'length_or_values' => null,
                'default_value' => null,
                'character_collation' => null,
                'column_attributes' => 'UNSIGNED',
                'is_nullable' => true,
                'index_type' => null,
                'is_auto_increment' => false,
                'column_comments' => 'User who last updated the record',
            ],
            [
                'column_name' => 'deleted_by',
                'data_type' => 'BIGINT',
                'length_or_values' => null,
                'default_value' => null,
                'character_collation' => null,
                'column_attributes' => 'UNSIGNED',
                'is_nullable' => true,
                'index_type' => null,
                'is_auto_increment' => false,
                'column_comments' => 'User who deleted the record',
            ],
            [
                'column_name' => 'restored_by',
                'data_type' => 'BIGINT',
                'length_or_values' => null,
                'default_value' => null,
                'character_collation' => null,
                'column_attributes' => 'UNSIGNED',
                'is_nullable' => true,
                'index_type' => null,
                'is_auto_increment' => false,
                'column_comments' => 'User who restored the record',
            ],
            [
                'column_name' => 'activated_by',
                'data_type' => 'BIGINT',
                'length_or_values' => null,
                'default_value' => null,
                'character_collation' => null,
                'column_attributes' => 'UNSIGNED',
                'is_nullable' => true,
                'index_type' => null,
                'is_auto_increment' => false,
                'column_comments' => 'User who activated the record',
            ],
            [
                'column_name' => 'deactivated_by',
                'data_type' => 'BIGINT',
                'length_or_values' => null,
                'default_value' => null,
                'character_collation' => null,
                'column_attributes' => 'UNSIGNED',
                'is_nullable' => true,
                'index_type' => null,
                'is_auto_increment' => false,
                'column_comments' => 'User who deactivated the record',
            ],
        ];

        foreach ($columns as $column) {
            DB::table('table_configurations')->insert([
                'table_name' => $table,
                'column_name' => $column['column_name'],
                'data_type' => $column['data_type'],
                'length_or_values' => $column['length_or_values'],
                'default_value' => $column['default_value'],
                'character_collation' => $column['character_collation'],
                'column_attributes' => $column['column_attributes'],
                'is_nullable' => $column['is_nullable'],
                'index_type' => $column['index_type'],
                'is_auto_increment' => $column['is_auto_increment'],
                'column_comments' => $column['column_comments'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}

//php artisan db:seed --class=TableConfigurationsSeeder
